# Generated by Django 3.0.8 on 2020-07-19 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atom_mgmt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atom',
            name='atom_position',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='atom',
            name='atom_weight',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='atom',
            name='cheat_days',
            field=models.IntegerField(default=0),
        ),
    ]
