# Generated by Django 3.0.8 on 2020-07-18 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_status', models.CharField(max_length=12)),
                ('user_name', models.CharField(max_length=24)),
                ('user_password', models.CharField(max_length=128)),
                ('user_mail', models.CharField(max_length=320)),
            ],
        ),
    ]
