# Generated by Django 3.0.8 on 2020-07-19 07:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user_mgmt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='user_date_created',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='user_mail_conf',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
