# Generated by Django 3.0.8 on 2020-07-19 07:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notes_mgmt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='note_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
