# Generated by Django 3.0.8 on 2020-07-19 07:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('track_mgmt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='score',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='track',
            name='track_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
